name: Make TWRP Device

on:
  workflow_dispatch:
    inputs:
      LIBRARY_NAME:
        description: 'LIBRARY_NAME'
        required: true
        default: 'Twrp_Device_Genter'
      IMG_URL:
        description: 'IMG_URL'
        required: true
        default: 'https://cdn.yiandrive.com/sites/yiandrive_1/_layouts/15/download.aspx?UniqueId=b8140b87-c899-4e68-a62b-db667de7941f&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvbW9zZWFjZy5zaGFyZXBvaW50LmNvbUBlN2ZkNjk2NS1lMDEwLTRmMzktOGNlNC1hZmQ1YzI5NDg5MTIiLCJpc3MiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAiLCJuYmYiOiIxNjY2MDczNjE0IiwiZXhwIjoiMTY2NjA3NzIxNCIsImVuZHBvaW50dXJsIjoiK2dWd3l4TVJzSEpvcENiOUVobFI0RnY1UlJhbnhVeEJOVlhwY0ZzenphST0iLCJlbmRwb2ludHVybExlbmd0aCI6IjEzNiIsImlzbG9vcGJhY2siOiJUcnVlIiwiY2lkIjoiTmpJM056a3hPREV0WkdSa01pMDBOVFJoTFRneU5HUXRZakppTVRnNFlqaGlOakF6IiwidmVyIjoiaGFzaGVkcHJvb2Z0b2tlbiIsInNpdGVpZCI6IlpEZGxNVE13T0dZdFpETXhOQzAwT0dVd0xXSXhaREl0TWprM016aGxObUkwTlRreSIsImFwcF9kaXNwbGF5bmFtZSI6InlpYW5kcml2ZV80NCIsImdpdmVuX25hbWUiOiLlrokiLCJmYW1pbHlfbmFtZSI6IuS6vyIsImFwcGlkIjoiNjM0OWU4N2MtOTQzYy00ZmVmLThkNDAtMTkxZTI2MDIxMmJiIiwidGlkIjoiZTdmZDY5NjUtZTAxMC00ZjM5LThjZTQtYWZkNWMyOTQ4OTEyIiwidXBuIjoieWlhbmRyaXZlQG1vc2VhY2cudG9wIiwicHVpZCI6IjEwMDMyMDAyMEM2QUQ4N0YiLCJjYWNoZWtleSI6IjBoLmZ8bWVtYmVyc2hpcHwxMDAzMjAwMjBjNmFkODdmQGxpdmUuY29tIiwic2NwIjoiYWxsZmlsZXMud3JpdGUiLCJ0dCI6IjIiLCJ1c2VQZXJzaXN0ZW50Q29va2llIjpudWxsLCJpcGFkZHIiOiIyMC4xOTAuMTQ0LjE3MCJ9.RjBvRFFqVjkvak5aV2IwTTRqK084aGZBQW9SZ0gxc295cnc0ZFhZUlZyUT0&ApiVersion=2.0'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-18.04
    
    steps:
    - name: Check Out
      uses: actions/checkout@main
      
    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y install python python3 python-pip python3-pip cpio wget
        pip3 install twrpdtgen
        mkdir dt
      
    - name: Download boot or recovery img
      run: |
        aria2c "${{ github.event.inputs.IMG_URL }}"
        ls
      
    - name: Start build
      run: |
        python3 -m twrpdtgen -o dt/ *.img

    - name: ZIP device tree
      run: |
        zip -r DeviceTree.zip ./dt

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./DeviceTree.zip
        name: TWRP_Device_Tree-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: DeviceTree for twrp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
