name: Make TWRP Device

on:
  workflow_dispatch:
    inputs:
      LIBRARY_NAME:
        description: 'LIBRARY_NAME'
        required: true
        default: 'Twrp_Device_Genter'
      IMG_URL:
        description: 'IMG_URL'
        required: true
        default: 'https://github.com/Xpsoted/android_device_qualcomm_qrd855-TWRP'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-18.04
    
    steps:
    - name: Check Out
      uses: actions/checkout@main
      
    - name: Prepare the environment
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d
        sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo apt -y autoremove --purge
        sudo apt -y autoclean
        sudo apt clean
        sudo apt update
        sudo apt -y install python python3 pip pip3 cpio wget
      
    - name: Set variables
      run: |
        echo "::set-output name=date::$(date +%F)"
      id: var
      
    - name: Install TWRP generator 
      run: |
        pip3 install twrpdtgen
        mkdir dt
    
    - name: Download boot or recovery img
      run: |
        wget ${{ github.event.inputs.IMG_URL }}
      
    - name: Start build
      run: |
        python3 -m twrpdtgen -o dt/ *.img

    - name: ZIP device tree
      run: |
        zip -r DeviceTree.zip ./dt

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./dt.zip
        name: TWRP_Device_Tree-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: DeviceTree for twrp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
